export const REFINANCE_DEMO_PRESETS = [
  {
    id: "rate-term-savings",
    label: "Rate-and-term savings",
    scenario: {
      loanPurpose: "rate_term_refinance",
      refinancePurpose: "lower_payment",
      propertyValue: "520000",
      estimatedPropertyValue: "520000",
      currentLoanBalance: "360000",
      currentInterestRate: "7.250",
      currentLoanTermYears: "30",
      currentRemainingTermYears: "28",
      newLoanAmount: "360000",
      estimatedNewLoanAmount: "360000",
      loanAmount: "360000",
      newInterestRate: "6.250",
      newLoanTermYears: "30",
      estimatedClosingCosts: "6500",
      creditScore: "740",
      occupancy: "primary",
      zipCode: "32801",
    },
  },
  {
    id: "cash-out-moderate",
    label: "Cash-out moderate",
    scenario: {
      loanPurpose: "cash_out_refinance",
      refinancePurpose: "cash_out",
      cashOutPurpose: "home improvement",
      cashOutGoal: "home improvement",
      propertyValue: "650000",
      estimatedPropertyValue: "650000",
      currentLoanBalance: "390000",
      currentInterestRate: "6.750",
      currentLoanTermYears: "30",
      currentRemainingTermYears: "26",
      requestedCashOut: "50000",
      desiredCashOut: "50000",
      newLoanAmount: "440000",
      estimatedNewLoanAmount: "440000",
      loanAmount: "440000",
      newInterestRate: "6.875",
      newLoanTermYears: "30",
      estimatedClosingCosts: "8200",
      creditScore: "720",
      occupancy: "primary",
      zipCode: "32801",
    },
  },
  {
    id: "debt-consolidation-improvement",
    label: "Debt consolidation improvement",
    scenario: {
      loanPurpose: "cash_out_refinance",
      refinancePurpose: "debt_consolidation",
      cashOutPurpose: "debt_consolidation",
      cashOutGoal: "debt_consolidation",
      propertyValue: "575000",
      estimatedPropertyValue: "575000",
      currentLoanBalance: "345000",
      currentInterestRate: "7.125",
      currentLoanTermYears: "30",
      currentRemainingTermYears: "27",
      requestedCashOut: "42000",
      desiredCashOut: "42000",
      debtConsolidationAmount: "42000",
      debtConsolidationMonthlyPayments: "1250",
      newLoanAmount: "387000",
      estimatedNewLoanAmount: "387000",
      loanAmount: "387000",
      newInterestRate: "6.750",
      newLoanTermYears: "30",
      estimatedClosingCosts: "7600",
      creditScore: "705",
      occupancy: "primary",
      zipCode: "32801",
    },
  },
  {
    id: "higher-payment",
    label: "Higher payment",
    scenario: {
      loanPurpose: "rate_term_refinance",
      refinancePurpose: "shorten_term",
      propertyValue: "480000",
      estimatedPropertyValue: "480000",
      currentLoanBalance: "310000",
      currentInterestRate: "5.250",
      currentLoanTermYears: "30",
      currentRemainingTermYears: "24",
      newLoanAmount: "310000",
      estimatedNewLoanAmount: "310000",
      loanAmount: "310000",
      newInterestRate: "6.500",
      newLoanTermYears: "15",
      estimatedClosingCosts: "5400",
      creditScore: "760",
      occupancy: "primary",
      zipCode: "32801",
    },
  },
  {
    id: "high-cash-out-warning",
    label: "High cash-out warning",
    scenario: {
      loanPurpose: "cash_out_refinance",
      refinancePurpose: "cash_out",
      cashOutPurpose: "large cash out test",
      cashOutGoal: "large cash out test",
      propertyValue: "450000",
      estimatedPropertyValue: "450000",
      currentLoanBalance: "410000",
      currentInterestRate: "6.875",
      currentLoanTermYears: "30",
      currentRemainingTermYears: "29",
      requestedCashOut: "85000",
      desiredCashOut: "85000",
      newLoanAmount: "495000",
      estimatedNewLoanAmount: "495000",
      loanAmount: "495000",
      newInterestRate: "7.125",
      newLoanTermYears: "30",
      estimatedClosingCosts: "9000",
      creditScore: "690",
      occupancy: "primary",
      zipCode: "32801",
    },
  },
];

export function getRefinanceDemoPreset(presetId) {
  return REFINANCE_DEMO_PRESETS.find((preset) => preset.id === presetId) || null;
}
